apiVersion: apps/v1
kind: Deployment
metadata:
  name: oomkilled-demo
  namespace: k8s-troubleshooting-lab
  labels:
    scenario: oomkilled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oomkilled-demo
  template:
    metadata:
      labels:
        app: oomkilled-demo
        scenario: oomkilled
    spec:
      containers:
        - name: app
          image: python:3.12-alpine
          command:
            - python
            - -c
            - |
              data = []
              while True:
                  data.append("x" * 1024 * 1024)
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
